/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.concurrent.TimeoutException;

import org.junit.jupiter.api.Test;

import in.techpro424.Library;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() throws TimeoutException {
        System.out.println(Library.downloadSingleVideo("dIWNltBsq10", "Enigmatic Encounter"));
    }
}
